language: objective-c
xcode_project: YetAnotherHTTPStub.xcodeproj
xcode_scheme: YetAnotherHTTPStub
osx_image: xcode8.3
env:
  - XCODE_SCHEME=YetAnotherHTTPStub
  - XCODE_SCHEME=Example
script: xcodebuild test -project YetAnotherHTTPStub.xcodeproj -scheme $XCODE_SCHEME -sdk iphonesimulator -destination "name=iPhone SE"
